import { SchoolInfo, Student, Teacher, Classroom, SppInvoice, StudentReport, AdministrativeLetter } from './types';

export const initialSchoolInfo: SchoolInfo = {
  name: 'SMP Negeri 4 Harapan Bangsa',
  npsn: '20103290',
  address: 'Jl. Pemuda No. 45, RT.02/RW.05, Rawamangun, Kec. Pulo Gadung, Kota Jakarta Timur',
  phone: '021-4890212',
  email: 'info@smpn4harapanbangsa.sch.id',
  website: 'www.smpn4harapanbangsa.sch.id',
  accreditation: 'A (Sangat Baik)',
  principalName: 'Drs. H. Mulyono, M.Pd.',
  principalNip: '197405121998031002',
  academicYear: '2025/2026',
  semester: 'Genap',
};

export const initialTeachers: Teacher[] = [
  {
    id: 't-1',
    nip: '198103152009042003',
    name: 'Siti Rahmawati, S.Pd.',
    gender: 'Perempuan',
    subject: 'Matematika',
    email: 'siti.rahma@gmail.com',
    phone: '081234567890',
    address: 'Perumahan Menteng Indah Blok B/12, Jakarta',
    position: 'Guru Mapel',
    status: 'Aktif',
  },
  {
    id: 't-2',
    nip: '198509202011011005',
    name: 'Budi Hartono, M.Si.',
    gender: 'Laki-laki',
    subject: 'Ilmu Pengetahuan Alam (IPA)',
    email: 'budi.hartono@yahoo.com',
    phone: '081398765432',
    address: 'Jl. Kebon Jeruk No. 8 A, Jakarta Selatan',
    position: 'Guru Mapel',
    status: 'Aktif',
  },
  {
    id: 't-3',
    nip: '197902042006042001',
    name: 'Retno Wulandari, S.S.',
    gender: 'Perempuan',
    subject: 'Bahasa Inggris',
    email: 'retno.wula99@gmail.com',
    phone: '085611223344',
    address: 'Kp. Melayu Kecil Gg. V No. 12, Jakarta Timur',
    position: 'Guru Kelas / Wali Kelas',
    status: 'Aktif',
  },
  {
    id: 't-4',
    nip: '198811052014021002',
    name: 'Ahmad Fauzi, S.Pd.',
    gender: 'Laki-laki',
    subject: 'Pendidikan Jasmani (PJOK)',
    email: 'ahmad_fauzi@outlook.com',
    phone: '087888776655',
    address: 'Jl. Raya Bogor KM 24, Ciracas, Jakarta',
    position: 'Guru Mapel',
    status: 'Aktif',
  },
  {
    id: 't-5',
    nip: '197607062002121004',
    name: 'Drs. Iwan Wijaya',
    gender: 'Laki-laki',
    subject: 'Bahasa Indonesia',
    email: 'iwan.wijaya@gmail.com',
    phone: '081211223399',
    address: 'Komp. DDN Blok A4 No. 19, Pondok Kelapa, Jakarta',
    position: 'Guru Kelas / Wali Kelas',
    status: 'Aktif',
  },
];

export const initialStudents: Student[] = [
  {
    id: 's-1',
    nisn: '0112345678',
    name: 'Aditya Pratama',
    gender: 'Laki-laki',
    birthPlace: 'Jakarta',
    birthDate: '2012-05-14',
    className: '7-A',
    address: 'Jl. Cipinang Muara III No. 56, RT.10/RW.04, Jakarta Timur',
    phone: '081288990011',
    parentName: 'Hendra Pratama',
    parentPhone: '081288990011',
    status: 'Aktif',
  },
  {
    id: 's-2',
    nisn: '0119876543',
    name: 'Anisa Rahmawati',
    gender: 'Perempuan',
    birthPlace: 'Bandung',
    birthDate: '2012-09-22',
    className: '7-A',
    address: 'Komp. Pondok Bambu Asri Gg. IV No. 2, Jakarta Timur',
    phone: '081322114455',
    parentName: 'Sujatmiko',
    parentPhone: '081322114450',
    status: 'Aktif',
  },
  {
    id: 's-3',
    nisn: '0105432189',
    name: 'Bagus Setiawan',
    gender: 'Laki-laki',
    birthPlace: 'Bekasi',
    birthDate: '2011-12-05',
    className: '8-A',
    address: 'Jl. Harapan Baru Baru VII Blok F No. 8, Bekasi Barat',
    phone: '085711225588',
    parentName: 'Agus Budiman',
    parentPhone: '085711225580',
    status: 'Aktif',
  },
  {
    id: 's-4',
    nisn: '0116677889',
    name: 'Citra Amelia',
    gender: 'Perempuan',
    birthPlace: 'Bogor',
    birthDate: '2012-01-30',
    className: '7-B',
    address: 'Jl. Otista III No. 14, Jatinegara, Jakarta Timur',
    phone: '089988776655',
    parentName: 'Rudi Arifin',
    parentPhone: '089988776650',
    status: 'Aktif',
  },
  {
    id: 's-5',
    nisn: '0098765432',
    name: 'Dimas Wijaya',
    gender: 'Laki-laki',
    birthPlace: 'Surabaya',
    birthDate: '2010-07-18',
    className: '9-A',
    address: 'Jl. Pisangan Baru Tengah No. 34, Matraman, Jakarta',
    phone: '088222333444',
    parentName: 'Lia Wijaya',
    parentPhone: '088222333440',
    status: 'Aktif',
  },
  {
    id: 's-6',
    nisn: '0112223334',
    name: 'Eka Putri Lestari',
    gender: 'Perempuan',
    birthPlace: 'Jakarta',
    birthDate: '2012-10-10',
    className: '7-B',
    address: 'Jl. Kayumanis Timur No. 15, Matraman, Jakarta Timur',
    phone: '081299900088',
    parentName: 'Bambang Lestari',
    parentPhone: '081299900080',
    status: 'Aktif',
  },
];

export const initialClassrooms: Classroom[] = [
  {
    id: 'c-1',
    className: '7-A',
    gradeLevel: 'VII',
    guardianTeacherId: 't-3', // Retno Wulandari
    room: 'Ruang Teori 01',
    capacity: 32,
  },
  {
    id: 'c-2',
    className: '7-B',
    gradeLevel: 'VII',
    guardianTeacherId: 't-5', // Drs. Iwan Wijaya
    room: 'Ruang Teori 02',
    capacity: 32,
  },
  {
    id: 'c-3',
    className: '8-A',
    gradeLevel: 'VIII',
    guardianTeacherId: 't-1', // Siti Rahmawati
    room: 'Ruang Teori 05',
    capacity: 30,
  },
  {
    id: 'c-4',
    className: '9-A',
    gradeLevel: 'IX',
    guardianTeacherId: 't-2', // Budi Hartono
    room: 'Ruang Teori 08',
    capacity: 30,
  },
];

export const initialSppInvoices: SppInvoice[] = [
  // s-1
  {
    id: 'f-1',
    studentId: 's-1',
    studentName: 'Aditya Pratama',
    className: '7-A',
    month: 'Januari',
    year: 2026,
    amount: 150000,
    status: 'Lunas',
    paymentDate: '2026-01-05',
    paymentMethod: 'Transfer',
    refNo: 'TRX-10023412',
  },
  {
    id: 'f-2',
    studentId: 's-1',
    studentName: 'Aditya Pratama',
    className: '7-A',
    month: 'Februari',
    year: 2026,
    amount: 150000,
    status: 'Lunas',
    paymentDate: '2026-02-04',
    paymentMethod: 'Tunai',
  },
  {
    id: 'f-3',
    studentId: 's-1',
    studentName: 'Aditya Pratama',
    className: '7-A',
    month: 'Maret',
    year: 2026,
    amount: 150000,
    status: 'Belum Lunas',
  },
  // s-2
  {
    id: 'f-4',
    studentId: 's-2',
    studentName: 'Anisa Rahmawati',
    className: '7-A',
    month: 'Januari',
    year: 2026,
    amount: 150000,
    status: 'Lunas',
    paymentDate: '2026-01-08',
    paymentMethod: 'Gopay/OVO',
    refNo: 'OVO-981726',
  },
  {
    id: 'f-5',
    studentId: 's-2',
    studentName: 'Anisa Rahmawati',
    className: '7-A',
    month: 'Februari',
    year: 2026,
    amount: 150000,
    status: 'Belum Lunas',
  },
  // s-3
  {
    id: 'f-6',
    studentId: 's-3',
    studentName: 'Bagus Setiawan',
    className: '8-A',
    month: 'Januari',
    year: 2026,
    amount: 150000,
    status: 'Lunas',
    paymentDate: '2026-01-10',
    paymentMethod: 'Tunai',
  },
  // s-4
  {
    id: 'f-7',
    studentId: 's-4',
    studentName: 'Citra Amelia',
    className: '7-B',
    month: 'Januari',
    year: 2026,
    amount: 150000,
    status: 'Belum Lunas',
  },
];

export const initialStudentReports: StudentReport[] = [
  {
    id: 'r-1',
    studentId: 's-1',
    studentName: 'Aditya Pratama',
    className: '7-A',
    semester: 'Genap',
    academicYear: '2025/2026',
    mathematics: 85,
    science: 82,
    english: 78,
    indonesian: 90,
    civics: 88,
    religion: 92,
    physicalEd: 85,
    art: 80,
    sickDays: 1,
    excusedDays: 0,
    unexcusedDays: 0,
    conduct: 'Amat Baik',
    notes: 'Aditya menunjukkan perkembangan prestasi yang luar biasa dalam bidang akademis terutama Matematika dan Agama. Pertahankan kebiasaan belajar ini!',
  },
  {
    id: 'r-2',
    studentId: 's-2',
    studentName: 'Anisa Rahmawati',
    className: '7-A',
    semester: 'Genap',
    academicYear: '2025/2026',
    mathematics: 92,
    science: 95,
    english: 89,
    indonesian: 87,
    civics: 91,
    religion: 94,
    physicalEd: 75,
    art: 88,
    sickDays: 0,
    excusedDays: 1,
    unexcusedDays: 0,
    conduct: 'Amat Baik',
    notes: 'Sangat pandai dalam bidang IPA dan Matematika. Sangat antusias dalam berdiskusi kelompok di kelas.',
  },
  {
    id: 'r-3',
    studentId: 's-3',
    studentName: 'Bagus Setiawan',
    className: '8-A',
    semester: 'Genap',
    academicYear: '2025/2026',
    mathematics: 70,
    science: 72,
    english: 68,
    indonesian: 75,
    civics: 78,
    religion: 80,
    physicalEd: 90,
    art: 75,
    sickDays: 3,
    excusedDays: 2,
    unexcusedDays: 1,
    conduct: 'Baik',
    notes: 'Bagus perlu meningkatkan disiplin dan fokus belajarnya kembali. Prestasi olahraganya sangat bagus.',
  },
];

export const initialLetters: AdministrativeLetter[] = [
  {
    id: 'l-1',
    referenceNumber: '421/0142/SMP-HB/2026',
    title: 'Surat Keterangan Siswa Aktif',
    type: 'Keterangan Aktif',
    recipientName: 'Kementrian Pendidikan / BPJS',
    dateCreated: '2026-03-01',
    studentId: 's-1',
    studentName: 'Aditya Pratama',
    content: 'Menerangkan dengan sesungguhnya bahwa siswa tersebut di bawah ini adalah benar-benar siswa aktif belajar di SMP Negeri 4 Harapan Bangsa untuk semester berjalan ini.',
  },
  {
    id: 'l-2',
    referenceNumber: '421/0155/SMP-HB/2026',
    title: 'Surat Panggilan Orang Tua',
    type: 'Panggilan Wali Murid',
    recipientName: 'Hendra Pratama (Wali dari Aditya Pratama)',
    dateCreated: '2026-03-15',
    studentId: 's-1',
    studentName: 'Aditya Pratama',
    content: 'Mengundang Bapak/Ibu Wali Murid hadir di Sekolah untuk berdiskusi perihal pembinaan keikutsertaan lomba olimpiade sains nasional tingkat kota.',
  },
];
